# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashBoardView.ui'
#
# Created: Fri Nov 14 09:45:33 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(801, 606)
        self.setWindowState(QtCore.Qt.WindowMaximized)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_19 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.adminButton = QtGui.QToolButton(self.centralwidget)
        self.adminButton.setStyleSheet(_fromUtf8("QToolButton{\n"
"    \n"
"    background-color:transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:checked,QToolButton:pressed{\n"
"    background-color: rgb(193,210,238);\n"
"    border: 1px solid rgb(60,127,177);\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color: rgb(224,232,246);\n"
"}"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/advanced.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.adminButton.setIcon(icon)
        self.adminButton.setIconSize(QtCore.QSize(64, 32))
        self.adminButton.setCheckable(True)
        self.adminButton.setAutoExclusive(True)
        self.adminButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.adminButton.setObjectName(_fromUtf8("adminButton"))
        self.horizontalLayout.addWidget(self.adminButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.profilButton = QtGui.QToolButton(self.centralwidget)
        self.profilButton.setStyleSheet(_fromUtf8("QToolButton{\n"
"    \n"
"    background-color:transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:checked,QToolButton:pressed{\n"
"    background-color: rgb(193,210,238);\n"
"    border: 1px solid rgb(60,127,177);\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color: rgb(224,232,246);\n"
"}"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/robot3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profilButton.setIcon(icon1)
        self.profilButton.setIconSize(QtCore.QSize(64, 32))
        self.profilButton.setCheckable(True)
        self.profilButton.setAutoExclusive(True)
        self.profilButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.profilButton.setObjectName(_fromUtf8("profilButton"))
        self.horizontalLayout.addWidget(self.profilButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.examButton = QtGui.QToolButton(self.centralwidget)
        self.examButton.setStyleSheet(_fromUtf8("QToolButton{\n"
"    \n"
"    background-color:transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:checked,QToolButton:pressed{\n"
"    background-color: rgb(193,210,238);\n"
"    border: 1px solid rgb(60,127,177);\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color: rgb(224,232,246);\n"
"}"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/application5.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.examButton.setIcon(icon2)
        self.examButton.setIconSize(QtCore.QSize(64, 32))
        self.examButton.setCheckable(True)
        self.examButton.setAutoExclusive(True)
        self.examButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.examButton.setObjectName(_fromUtf8("examButton"))
        self.horizontalLayout.addWidget(self.examButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.resultsButton = QtGui.QToolButton(self.centralwidget)
        self.resultsButton.setStyleSheet(_fromUtf8("QToolButton{\n"
"    \n"
"    background-color:transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:checked,QToolButton:pressed{\n"
"    background-color: rgb(193,210,238);\n"
"    border: 1px solid rgb(60,127,177);\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color: rgb(224,232,246);\n"
"}"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/pie3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resultsButton.setIcon(icon3)
        self.resultsButton.setIconSize(QtCore.QSize(64, 32))
        self.resultsButton.setCheckable(True)
        self.resultsButton.setAutoExclusive(True)
        self.resultsButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.resultsButton.setObjectName(_fromUtf8("resultsButton"))
        self.horizontalLayout.addWidget(self.resultsButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.aboutButton = QtGui.QToolButton(self.centralwidget)
        self.aboutButton.setStyleSheet(_fromUtf8("QToolButton{\n"
"    \n"
"    background-color:transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:checked,QToolButton:pressed{\n"
"    background-color: rgb(193,210,238);\n"
"    border: 1px solid rgb(60,127,177);\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color: rgb(224,232,246);\n"
"}"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/information12.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutButton.setIcon(icon4)
        self.aboutButton.setIconSize(QtCore.QSize(64, 32))
        self.aboutButton.setCheckable(True)
        self.aboutButton.setAutoExclusive(True)
        self.aboutButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.aboutButton.setObjectName(_fromUtf8("aboutButton"))
        self.horizontalLayout.addWidget(self.aboutButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.logoutButton = QtGui.QToolButton(self.centralwidget)
        self.logoutButton.setStyleSheet(_fromUtf8("QToolButton{\n"
"    \n"
"    background-color:transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:checked,QToolButton:pressed{\n"
"    background-color: rgb(193,210,238);\n"
"    border: 1px solid rgb(60,127,177);\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color: rgb(224,232,246);\n"
"}"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/job1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutButton.setIcon(icon5)
        self.logoutButton.setIconSize(QtCore.QSize(64, 32))
        self.logoutButton.setCheckable(True)
        self.logoutButton.setAutoExclusive(True)
        self.logoutButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.logoutButton.setObjectName(_fromUtf8("logoutButton"))
        self.horizontalLayout.addWidget(self.logoutButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.gridLayout_19.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_19.addWidget(self.line, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.welcomeLabel = QtGui.QLabel(self.centralwidget)
        self.welcomeLabel.setObjectName(_fromUtf8("welcomeLabel"))
        self.horizontalLayout_2.addWidget(self.welcomeLabel)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.currentTimeLabel = QtGui.QLabel(self.centralwidget)
        self.currentTimeLabel.setObjectName(_fromUtf8("currentTimeLabel"))
        self.horizontalLayout_2.addWidget(self.currentTimeLabel)
        self.gridLayout_19.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.adminPage = QtGui.QWidget()
        self.adminPage.setObjectName(_fromUtf8("adminPage"))
        self.gridLayout_13 = QtGui.QGridLayout(self.adminPage)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.tabWidget_2 = QtGui.QTabWidget(self.adminPage)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_21 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.topicListCombobox = QtGui.QComboBox(self.tab_2)
        self.topicListCombobox.setMinimumSize(QtCore.QSize(180, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.topicListCombobox.setFont(font)
        self.topicListCombobox.setObjectName(_fromUtf8("topicListCombobox"))
        self.gridLayout_21.addWidget(self.topicListCombobox, 0, 0, 1, 1)
        self.refreshTopicButton = QtGui.QPushButton(self.tab_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/synchronize2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshTopicButton.setIcon(icon6)
        self.refreshTopicButton.setObjectName(_fromUtf8("refreshTopicButton"))
        self.gridLayout_21.addWidget(self.refreshTopicButton, 0, 1, 1, 1)
        self.addNewQuestionButton = QtGui.QPushButton(self.tab_2)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addNewQuestionButton.setIcon(icon7)
        self.addNewQuestionButton.setObjectName(_fromUtf8("addNewQuestionButton"))
        self.gridLayout_21.addWidget(self.addNewQuestionButton, 0, 2, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(61, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem9, 0, 3, 1, 1)
        self.editQuestionButton = QtGui.QPushButton(self.tab_2)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/ceo1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editQuestionButton.setIcon(icon8)
        self.editQuestionButton.setObjectName(_fromUtf8("editQuestionButton"))
        self.gridLayout_21.addWidget(self.editQuestionButton, 0, 4, 1, 1)
        self.deleteQuestionButton = QtGui.QPushButton(self.tab_2)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/bin.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteQuestionButton.setIcon(icon9)
        self.deleteQuestionButton.setObjectName(_fromUtf8("deleteQuestionButton"))
        self.gridLayout_21.addWidget(self.deleteQuestionButton, 0, 5, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_21.addWidget(self.label_22, 1, 0, 1, 1)
        self.scrollArea_6 = QtGui.QScrollArea(self.tab_2)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName(_fromUtf8("scrollArea_6"))
        self.scrollAreaWidgetContents_6 = QtGui.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 739, 164))
        self.scrollAreaWidgetContents_6.setObjectName(_fromUtf8("scrollAreaWidgetContents_6"))
        self.gridLayout_11 = QtGui.QGridLayout(self.scrollAreaWidgetContents_6)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.questionsListTable = QtGui.QTableWidget(self.scrollAreaWidgetContents_6)
        self.questionsListTable.setObjectName(_fromUtf8("questionsListTable"))
        self.questionsListTable.setColumnCount(2)
        self.questionsListTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.questionsListTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.questionsListTable.setHorizontalHeaderItem(1, item)
        self.gridLayout_11.addWidget(self.questionsListTable, 0, 0, 1, 1)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout_21.addWidget(self.scrollArea_6, 2, 0, 1, 6)
        self.label_23 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_21.addWidget(self.label_23, 3, 0, 1, 1)
        self.scrollArea_7 = QtGui.QScrollArea(self.tab_2)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName(_fromUtf8("scrollArea_7"))
        self.scrollAreaWidgetContents_7 = QtGui.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 739, 164))
        self.scrollAreaWidgetContents_7.setObjectName(_fromUtf8("scrollAreaWidgetContents_7"))
        self.gridLayout_12 = QtGui.QGridLayout(self.scrollAreaWidgetContents_7)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.answersListTable = QtGui.QTableWidget(self.scrollAreaWidgetContents_7)
        self.answersListTable.setObjectName(_fromUtf8("answersListTable"))
        self.answersListTable.setColumnCount(4)
        self.answersListTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.answersListTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.answersListTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.answersListTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.answersListTable.setHorizontalHeaderItem(3, item)
        self.gridLayout_12.addWidget(self.answersListTable, 0, 0, 1, 1)
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_7)
        self.gridLayout_21.addWidget(self.scrollArea_7, 4, 0, 1, 6)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/question-mark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_2, icon10, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_18 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_36 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_18.addWidget(self.label_36, 0, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(544, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem10, 0, 1, 1, 1)
        self.lessCheckbox = QtGui.QCheckBox(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lessCheckbox.setFont(font)
        self.lessCheckbox.setObjectName(_fromUtf8("lessCheckbox"))
        self.gridLayout_18.addWidget(self.lessCheckbox, 0, 2, 1, 1)
        self.moreChecbox = QtGui.QCheckBox(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.moreChecbox.setFont(font)
        self.moreChecbox.setObjectName(_fromUtf8("moreChecbox"))
        self.gridLayout_18.addWidget(self.moreChecbox, 0, 3, 1, 1)
        self.equalCheckbox = QtGui.QCheckBox(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.equalCheckbox.setFont(font)
        self.equalCheckbox.setObjectName(_fromUtf8("equalCheckbox"))
        self.gridLayout_18.addWidget(self.equalCheckbox, 0, 4, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_28 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_10.addWidget(self.label_28, 1, 0, 1, 1)
        self.emailFilterBox = QtGui.QLineEdit(self.tab_3)
        self.emailFilterBox.setMaxLength(255)
        self.emailFilterBox.setObjectName(_fromUtf8("emailFilterBox"))
        self.gridLayout_10.addWidget(self.emailFilterBox, 2, 5, 1, 1)
        self.ageFilterBox = QtGui.QLineEdit(self.tab_3)
        self.ageFilterBox.setMaxLength(10)
        self.ageFilterBox.setObjectName(_fromUtf8("ageFilterBox"))
        self.gridLayout_10.addWidget(self.ageFilterBox, 1, 5, 1, 1)
        self.filterUsersButton = QtGui.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.filterUsersButton.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/search15.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filterUsersButton.setIcon(icon11)
        self.filterUsersButton.setObjectName(_fromUtf8("filterUsersButton"))
        self.gridLayout_10.addWidget(self.filterUsersButton, 3, 6, 1, 1)
        self.lastNameFilterBox = QtGui.QLineEdit(self.tab_3)
        self.lastNameFilterBox.setMaxLength(255)
        self.lastNameFilterBox.setObjectName(_fromUtf8("lastNameFilterBox"))
        self.gridLayout_10.addWidget(self.lastNameFilterBox, 1, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_10.addWidget(self.label_35, 3, 0, 1, 1)
        self.addressFilterBox = QtGui.QLineEdit(self.tab_3)
        self.addressFilterBox.setMaxLength(255)
        self.addressFilterBox.setObjectName(_fromUtf8("addressFilterBox"))
        self.gridLayout_10.addWidget(self.addressFilterBox, 2, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_10.addWidget(self.label_32, 2, 2, 1, 1)
        self.cityFilterBox = QtGui.QLineEdit(self.tab_3)
        self.cityFilterBox.setMaxLength(255)
        self.cityFilterBox.setObjectName(_fromUtf8("cityFilterBox"))
        self.gridLayout_10.addWidget(self.cityFilterBox, 1, 3, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_10.addWidget(self.label_33, 1, 2, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_10.addWidget(self.label_30, 1, 4, 1, 1)
        self.label_34 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_10.addWidget(self.label_34, 3, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_10.addWidget(self.label_31, 2, 4, 1, 1)
        self.phoneFilterBox = QtGui.QLineEdit(self.tab_3)
        self.phoneFilterBox.setMaxLength(100)
        self.phoneFilterBox.setObjectName(_fromUtf8("phoneFilterBox"))
        self.gridLayout_10.addWidget(self.phoneFilterBox, 3, 3, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_10.addWidget(self.label_29, 2, 0, 1, 1)
        self.firstNameFilterBox = QtGui.QLineEdit(self.tab_3)
        self.firstNameFilterBox.setMaxLength(255)
        self.firstNameFilterBox.setObjectName(_fromUtf8("firstNameFilterBox"))
        self.gridLayout_10.addWidget(self.firstNameFilterBox, 2, 1, 1, 1)
        self.registeredFilterBox = QtGui.QLineEdit(self.tab_3)
        self.registeredFilterBox.setMaxLength(10)
        self.registeredFilterBox.setObjectName(_fromUtf8("registeredFilterBox"))
        self.gridLayout_10.addWidget(self.registeredFilterBox, 3, 1, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_10, 1, 0, 1, 5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.editUserButton = QtGui.QPushButton(self.tab_3)
        self.editUserButton.setIcon(icon8)
        self.editUserButton.setObjectName(_fromUtf8("editUserButton"))
        self.horizontalLayout_6.addWidget(self.editUserButton)
        self.deleteUserButton = QtGui.QPushButton(self.tab_3)
        self.deleteUserButton.setIcon(icon9)
        self.deleteUserButton.setObjectName(_fromUtf8("deleteUserButton"))
        self.horizontalLayout_6.addWidget(self.deleteUserButton)
        self.gridLayout_18.addLayout(self.horizontalLayout_6, 2, 0, 1, 5)
        self.scrollArea_5 = QtGui.QScrollArea(self.tab_3)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName(_fromUtf8("scrollArea_5"))
        self.scrollAreaWidgetContents_5 = QtGui.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 739, 262))
        self.scrollAreaWidgetContents_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_5"))
        self.gridLayout_9 = QtGui.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.usersListTable = QtGui.QTableWidget(self.scrollAreaWidgetContents_5)
        self.usersListTable.setObjectName(_fromUtf8("usersListTable"))
        self.usersListTable.setColumnCount(9)
        self.usersListTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.usersListTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.usersListTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.usersListTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.usersListTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.usersListTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.usersListTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.usersListTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.usersListTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.usersListTable.setHorizontalHeaderItem(8, item)
        self.gridLayout_9.addWidget(self.usersListTable, 0, 0, 1, 1)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_18.addWidget(self.scrollArea_5, 3, 0, 1, 5)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/group_edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_3, icon12, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem12 = QtGui.QSpacerItem(361, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem12, 5, 0, 1, 3)
        spacerItem13 = QtGui.QSpacerItem(20, 133, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem13, 4, 4, 1, 1)
        self.scrollArea_4 = QtGui.QScrollArea(self.tab_4)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 317, 133))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.answersTable = QtGui.QTableWidget(self.scrollAreaWidgetContents_4)
        self.answersTable.setObjectName(_fromUtf8("answersTable"))
        self.answersTable.setColumnCount(4)
        self.answersTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.answersTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.answersTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.answersTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.answersTable.setHorizontalHeaderItem(3, item)
        self.gridLayout_7.addWidget(self.answersTable, 0, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_8.addWidget(self.scrollArea_4, 4, 3, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(258, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem14, 7, 0, 1, 2)
        spacerItem15 = QtGui.QSpacerItem(339, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem15, 6, 3, 1, 1)
        self.addNewTopicBox = QtGui.QLineEdit(self.tab_4)
        self.addNewTopicBox.setMaxLength(255)
        self.addNewTopicBox.setObjectName(_fromUtf8("addNewTopicBox"))
        self.gridLayout_8.addWidget(self.addNewTopicBox, 6, 1, 1, 2)
        self.label_21 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_8.addWidget(self.label_21, 6, 0, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(339, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem16, 7, 3, 1, 1)
        self.addNewTopicButton = QtGui.QPushButton(self.tab_4)
        self.addNewTopicButton.setIcon(icon7)
        self.addNewTopicButton.setObjectName(_fromUtf8("addNewTopicButton"))
        self.gridLayout_8.addWidget(self.addNewTopicButton, 7, 2, 1, 1)
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_4)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 713, 132))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.topicsTable = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        self.topicsTable.setObjectName(_fromUtf8("topicsTable"))
        self.topicsTable.setColumnCount(3)
        self.topicsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.topicsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.topicsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.topicsTable.setHorizontalHeaderItem(2, item)
        self.topicsTable.horizontalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.topicsTable, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_8.addWidget(self.scrollArea_2, 2, 0, 1, 4)
        spacerItem17 = QtGui.QSpacerItem(20, 132, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem17, 2, 4, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_8.addWidget(self.label_12, 3, 3, 1, 1)
        self.scrollArea_3 = QtGui.QScrollArea(self.tab_4)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 388, 133))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.questionsTable = QtGui.QTableWidget(self.scrollAreaWidgetContents_2)
        self.questionsTable.setObjectName(_fromUtf8("questionsTable"))
        self.questionsTable.setColumnCount(2)
        self.questionsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.questionsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.questionsTable.setHorizontalHeaderItem(1, item)
        self.gridLayout_4.addWidget(self.questionsTable, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_8.addWidget(self.scrollArea_3, 4, 0, 1, 3)
        self.label_10 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_8.addWidget(self.label_10, 3, 0, 1, 2)
        self.label_11 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_8.addWidget(self.label_11, 0, 0, 1, 1)
        self.deleteTopicButton = QtGui.QPushButton(self.tab_4)
        self.deleteTopicButton.setIcon(icon9)
        self.deleteTopicButton.setObjectName(_fromUtf8("deleteTopicButton"))
        self.gridLayout_8.addWidget(self.deleteTopicButton, 0, 2, 1, 1)
        self.editTopicButton = QtGui.QPushButton(self.tab_4)
        self.editTopicButton.setIcon(icon8)
        self.editTopicButton.setObjectName(_fromUtf8("editTopicButton"))
        self.gridLayout_8.addWidget(self.editTopicButton, 0, 1, 1, 1)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/diary1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_4, icon13, _fromUtf8(""))
        self.gridLayout_13.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.adminPage)
        self.profilPage = QtGui.QWidget()
        self.profilPage.setObjectName(_fromUtf8("profilPage"))
        self.gridLayout_2 = QtGui.QGridLayout(self.profilPage)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.profilPage)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tab)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem18, 9, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 0, 2, 1, 1)
        self.cityEditBox = QtGui.QLineEdit(self.tab)
        self.cityEditBox.setMaxLength(255)
        self.cityEditBox.setObjectName(_fromUtf8("cityEditBox"))
        self.gridLayout_6.addWidget(self.cityEditBox, 10, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_6.addWidget(self.label_20, 14, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_6.addWidget(self.label_18, 8, 2, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem19, 3, 0, 1, 1)
        self.addressEditBox = QtGui.QLineEdit(self.tab)
        self.addressEditBox.setMaxLength(255)
        self.addressEditBox.setObjectName(_fromUtf8("addressEditBox"))
        self.gridLayout_6.addWidget(self.addressEditBox, 12, 1, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem20, 11, 0, 1, 1)
        self.passwordEditBox = QtGui.QLineEdit(self.tab)
        self.passwordEditBox.setMaxLength(255)
        self.passwordEditBox.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordEditBox.setObjectName(_fromUtf8("passwordEditBox"))
        self.gridLayout_6.addWidget(self.passwordEditBox, 6, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_6.addWidget(self.label_17, 6, 2, 1, 1)
        self.phoneEditBox = QtGui.QLineEdit(self.tab)
        self.phoneEditBox.setMaxLength(100)
        self.phoneEditBox.setObjectName(_fromUtf8("phoneEditBox"))
        self.gridLayout_6.addWidget(self.phoneEditBox, 14, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_6.addWidget(self.label_16, 4, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.passwordAgainEditBox = QtGui.QLineEdit(self.tab)
        self.passwordAgainEditBox.setMaxLength(255)
        self.passwordAgainEditBox.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordAgainEditBox.setObjectName(_fromUtf8("passwordAgainEditBox"))
        self.gridLayout_6.addWidget(self.passwordAgainEditBox, 8, 1, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem21, 13, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 10, 0, 1, 1)
        self.emailEditBox = QtGui.QLineEdit(self.tab)
        self.emailEditBox.setMaxLength(255)
        self.emailEditBox.setObjectName(_fromUtf8("emailEditBox"))
        self.gridLayout_6.addWidget(self.emailEditBox, 4, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 2, 0, 1, 1)
        self.lastNameEditBox = QtGui.QLineEdit(self.tab)
        self.lastNameEditBox.setMaxLength(255)
        self.lastNameEditBox.setObjectName(_fromUtf8("lastNameEditBox"))
        self.gridLayout_6.addWidget(self.lastNameEditBox, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 8, 0, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem22, 7, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 6, 0, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem23, 5, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_6.addWidget(self.label_19, 12, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_6.addWidget(self.label_15, 2, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 4, 0, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem24, 1, 0, 1, 1)
        self.firstNameEditBox = QtGui.QLineEdit(self.tab)
        self.firstNameEditBox.setMaxLength(255)
        self.firstNameEditBox.setObjectName(_fromUtf8("firstNameEditBox"))
        self.gridLayout_6.addWidget(self.firstNameEditBox, 2, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.tab)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_6.addWidget(self.label_38, 16, 0, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem25, 15, 0, 1, 1)
        self.birthdayEditBox = QtGui.QLineEdit(self.tab)
        self.birthdayEditBox.setObjectName(_fromUtf8("birthdayEditBox"))
        self.gridLayout_6.addWidget(self.birthdayEditBox, 16, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_6, 0, 0, 1, 2)
        spacerItem26 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem26, 1, 0, 1, 1)
        self.userEditButton = QtGui.QPushButton(self.tab)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/user_edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userEditButton.setIcon(icon14)
        self.userEditButton.setObjectName(_fromUtf8("userEditButton"))
        self.gridLayout_14.addWidget(self.userEditButton, 1, 1, 2, 1)
        spacerItem27 = QtGui.QSpacerItem(655, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem27, 2, 0, 1, 1)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/technical.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon15, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.profilPage)
        self.examPage = QtGui.QWidget()
        self.examPage.setObjectName(_fromUtf8("examPage"))
        self.gridLayout = QtGui.QGridLayout(self.examPage)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.examPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.maxPointLabelText = QtGui.QLabel(self.examPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maxPointLabelText.setFont(font)
        self.maxPointLabelText.setObjectName(_fromUtf8("maxPointLabelText"))
        self.gridLayout.addWidget(self.maxPointLabelText, 0, 3, 1, 1)
        self.maxPointsLabel = QtGui.QLabel(self.examPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.maxPointsLabel.setFont(font)
        self.maxPointsLabel.setText(_fromUtf8(""))
        self.maxPointsLabel.setObjectName(_fromUtf8("maxPointsLabel"))
        self.gridLayout.addWidget(self.maxPointsLabel, 0, 4, 1, 2)
        self.label_3 = QtGui.QLabel(self.examPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 6, 1, 1)
        self.examsTypeCombobox = QtGui.QComboBox(self.examPage)
        self.examsTypeCombobox.setMinimumSize(QtCore.QSize(180, 21))
        self.examsTypeCombobox.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.examsTypeCombobox.setFont(font)
        self.examsTypeCombobox.setObjectName(_fromUtf8("examsTypeCombobox"))
        self.gridLayout.addWidget(self.examsTypeCombobox, 1, 0, 1, 1)
        self.startExamButton = QtGui.QPushButton(self.examPage)
        self.startExamButton.setMinimumSize(QtCore.QSize(0, 24))
        self.startExamButton.setMaximumSize(QtCore.QSize(120, 25))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/mouse2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startExamButton.setIcon(icon16)
        self.startExamButton.setObjectName(_fromUtf8("startExamButton"))
        self.gridLayout.addWidget(self.startExamButton, 1, 1, 1, 1)
        self.yourResultLabelText = QtGui.QLabel(self.examPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.yourResultLabelText.setFont(font)
        self.yourResultLabelText.setObjectName(_fromUtf8("yourResultLabelText"))
        self.gridLayout.addWidget(self.yourResultLabelText, 1, 3, 1, 1)
        self.yourPointsLabel = QtGui.QLabel(self.examPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.yourPointsLabel.setFont(font)
        self.yourPointsLabel.setText(_fromUtf8(""))
        self.yourPointsLabel.setObjectName(_fromUtf8("yourPointsLabel"))
        self.gridLayout.addWidget(self.yourPointsLabel, 1, 4, 1, 2)
        self.lcdNumber = QtGui.QLCDNumber(self.examPage)
        self.lcdNumber.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"background-color: rgb(0, 0, 0)\n"
"}\n"
"\n"
""))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.gridLayout.addWidget(self.lcdNumber, 1, 6, 1, 1)
        spacerItem28 = QtGui.QSpacerItem(241, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem28, 2, 0, 1, 2)
        spacerItem29 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem29, 2, 2, 1, 1)
        spacerItem30 = QtGui.QSpacerItem(195, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem30, 2, 3, 1, 2)
        spacerItem31 = QtGui.QSpacerItem(134, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem31, 2, 5, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.examPage)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 763, 376))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.currentExamTableView = QtGui.QTableView(self.scrollAreaWidgetContents_3)
        self.currentExamTableView.setObjectName(_fromUtf8("currentExamTableView"))
        self.currentExamTableView.horizontalHeader().setVisible(False)
        self.currentExamTableView.horizontalHeader().setHighlightSections(False)
        self.currentExamTableView.verticalHeader().setHighlightSections(False)
        self.gridLayout_5.addWidget(self.currentExamTableView, 0, 0, 1, 2)
        spacerItem32 = QtGui.QSpacerItem(654, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem32, 1, 0, 1, 1)
        self.sendExamButton = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/selected2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendExamButton.setIcon(icon17)
        self.sendExamButton.setObjectName(_fromUtf8("sendExamButton"))
        self.gridLayout_5.addWidget(self.sendExamButton, 1, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea, 3, 0, 1, 7)
        self.stackedWidget.addWidget(self.examPage)
        self.resultsPage = QtGui.QWidget()
        self.resultsPage.setObjectName(_fromUtf8("resultsPage"))
        self.gridLayout_16 = QtGui.QGridLayout(self.resultsPage)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.myResultsBarChartButton = QtGui.QPushButton(self.resultsPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.myResultsBarChartButton.setFont(font)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/dashboard/file3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.myResultsBarChartButton.setIcon(icon18)
        self.myResultsBarChartButton.setObjectName(_fromUtf8("myResultsBarChartButton"))
        self.horizontalLayout_4.addWidget(self.myResultsBarChartButton)
        self.showUserResultsBarChartButton = QtGui.QPushButton(self.resultsPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.showUserResultsBarChartButton.setFont(font)
        self.showUserResultsBarChartButton.setIcon(icon18)
        self.showUserResultsBarChartButton.setFlat(False)
        self.showUserResultsBarChartButton.setObjectName(_fromUtf8("showUserResultsBarChartButton"))
        self.horizontalLayout_4.addWidget(self.showUserResultsBarChartButton)
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem33)
        self.gridLayout_16.addLayout(self.horizontalLayout_4, 0, 0, 1, 2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_37 = QtGui.QLabel(self.resultsPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_5.addWidget(self.label_37)
        spacerItem34 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem34)
        self.resultLessCheckbox = QtGui.QCheckBox(self.resultsPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resultLessCheckbox.setFont(font)
        self.resultLessCheckbox.setObjectName(_fromUtf8("resultLessCheckbox"))
        self.horizontalLayout_5.addWidget(self.resultLessCheckbox)
        self.resultMoreCheckbox = QtGui.QCheckBox(self.resultsPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resultMoreCheckbox.setFont(font)
        self.resultMoreCheckbox.setObjectName(_fromUtf8("resultMoreCheckbox"))
        self.horizontalLayout_5.addWidget(self.resultMoreCheckbox)
        self.resultEqualCheckbox = QtGui.QCheckBox(self.resultsPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resultEqualCheckbox.setFont(font)
        self.resultEqualCheckbox.setObjectName(_fromUtf8("resultEqualCheckbox"))
        self.horizontalLayout_5.addWidget(self.resultEqualCheckbox)
        self.gridLayout_16.addLayout(self.horizontalLayout_5, 1, 0, 1, 2)
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_25 = QtGui.QLabel(self.resultsPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_17.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.resultsPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_17.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.resultsPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_17.addWidget(self.label_26, 0, 2, 1, 1)
        self.topicsFilterBox = QtGui.QLineEdit(self.resultsPage)
        self.topicsFilterBox.setMaxLength(255)
        self.topicsFilterBox.setObjectName(_fromUtf8("topicsFilterBox"))
        self.gridLayout_17.addWidget(self.topicsFilterBox, 0, 1, 1, 1)
        self.filterResultButton = QtGui.QPushButton(self.resultsPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.filterResultButton.setFont(font)
        self.filterResultButton.setIcon(icon11)
        self.filterResultButton.setObjectName(_fromUtf8("filterResultButton"))
        self.gridLayout_17.addWidget(self.filterResultButton, 1, 6, 1, 1)
        self.scoreFilterBox = QtGui.QLineEdit(self.resultsPage)
        self.scoreFilterBox.setMaxLength(9999)
        self.scoreFilterBox.setObjectName(_fromUtf8("scoreFilterBox"))
        self.gridLayout_17.addWidget(self.scoreFilterBox, 0, 3, 1, 1)
        self.topicsDateFilterBox = QtGui.QLineEdit(self.resultsPage)
        self.topicsDateFilterBox.setMaxLength(10)
        self.topicsDateFilterBox.setObjectName(_fromUtf8("topicsDateFilterBox"))
        self.gridLayout_17.addWidget(self.topicsDateFilterBox, 1, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.resultsPage)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_17.addWidget(self.label_39, 1, 2, 1, 1)
        self.resultPageEmailFilterBox = QtGui.QLineEdit(self.resultsPage)
        self.resultPageEmailFilterBox.setObjectName(_fromUtf8("resultPageEmailFilterBox"))
        self.gridLayout_17.addWidget(self.resultPageEmailFilterBox, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.resultsPage)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_17.addWidget(self.label_4, 1, 4, 1, 1)
        self.label = QtGui.QLabel(self.resultsPage)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_17.addWidget(self.label, 0, 4, 1, 1)
        self.resultPageFirstNameFilterBox = QtGui.QLineEdit(self.resultsPage)
        self.resultPageFirstNameFilterBox.setObjectName(_fromUtf8("resultPageFirstNameFilterBox"))
        self.gridLayout_17.addWidget(self.resultPageFirstNameFilterBox, 1, 5, 1, 1)
        self.resultPageLastNameFilterBox = QtGui.QLineEdit(self.resultsPage)
        self.resultPageLastNameFilterBox.setObjectName(_fromUtf8("resultPageLastNameFilterBox"))
        self.gridLayout_17.addWidget(self.resultPageLastNameFilterBox, 0, 5, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_17, 2, 0, 2, 2)
        self.scrollArea_8 = QtGui.QScrollArea(self.resultsPage)
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName(_fromUtf8("scrollArea_8"))
        self.scrollAreaWidgetContents_8 = QtGui.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 763, 333))
        self.scrollAreaWidgetContents_8.setObjectName(_fromUtf8("scrollAreaWidgetContents_8"))
        self.gridLayout_15 = QtGui.QGridLayout(self.scrollAreaWidgetContents_8)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.usersResultsListTable = QtGui.QTableWidget(self.scrollAreaWidgetContents_8)
        self.usersResultsListTable.setObjectName(_fromUtf8("usersResultsListTable"))
        self.usersResultsListTable.setColumnCount(6)
        self.usersResultsListTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.usersResultsListTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.usersResultsListTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.usersResultsListTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.usersResultsListTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.usersResultsListTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.usersResultsListTable.setHorizontalHeaderItem(5, item)
        self.gridLayout_15.addWidget(self.usersResultsListTable, 0, 0, 1, 1)
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_8)
        self.gridLayout_16.addWidget(self.scrollArea_8, 4, 0, 1, 2)
        self.stackedWidget.addWidget(self.resultsPage)
        self.gridLayout_19.addWidget(self.stackedWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.topicsFilterBox, self.topicsDateFilterBox)
        MainWindow.setTabOrder(self.topicsDateFilterBox, self.scoreFilterBox)
        MainWindow.setTabOrder(self.scoreFilterBox, self.resultPageEmailFilterBox)
        MainWindow.setTabOrder(self.resultPageEmailFilterBox, self.resultPageLastNameFilterBox)
        MainWindow.setTabOrder(self.resultPageLastNameFilterBox, self.resultPageFirstNameFilterBox)
        MainWindow.setTabOrder(self.resultPageFirstNameFilterBox, self.lastNameEditBox)
        MainWindow.setTabOrder(self.lastNameEditBox, self.firstNameEditBox)
        MainWindow.setTabOrder(self.firstNameEditBox, self.emailEditBox)
        MainWindow.setTabOrder(self.emailEditBox, self.passwordEditBox)
        MainWindow.setTabOrder(self.passwordEditBox, self.passwordAgainEditBox)
        MainWindow.setTabOrder(self.passwordAgainEditBox, self.cityEditBox)
        MainWindow.setTabOrder(self.cityEditBox, self.addressEditBox)
        MainWindow.setTabOrder(self.addressEditBox, self.phoneEditBox)
        MainWindow.setTabOrder(self.phoneEditBox, self.birthdayEditBox)
        MainWindow.setTabOrder(self.birthdayEditBox, self.lastNameFilterBox)
        MainWindow.setTabOrder(self.lastNameFilterBox, self.firstNameFilterBox)
        MainWindow.setTabOrder(self.firstNameFilterBox, self.registeredFilterBox)
        MainWindow.setTabOrder(self.registeredFilterBox, self.cityFilterBox)
        MainWindow.setTabOrder(self.cityFilterBox, self.addressFilterBox)
        MainWindow.setTabOrder(self.addressFilterBox, self.phoneFilterBox)
        MainWindow.setTabOrder(self.phoneFilterBox, self.ageFilterBox)
        MainWindow.setTabOrder(self.ageFilterBox, self.emailFilterBox)
        MainWindow.setTabOrder(self.emailFilterBox, self.equalCheckbox)
        MainWindow.setTabOrder(self.equalCheckbox, self.filterUsersButton)
        MainWindow.setTabOrder(self.filterUsersButton, self.scrollArea_5)
        MainWindow.setTabOrder(self.scrollArea_5, self.usersListTable)
        MainWindow.setTabOrder(self.usersListTable, self.scrollArea_2)
        MainWindow.setTabOrder(self.scrollArea_2, self.topicsTable)
        MainWindow.setTabOrder(self.topicsTable, self.scrollArea_3)
        MainWindow.setTabOrder(self.scrollArea_3, self.questionsTable)
        MainWindow.setTabOrder(self.questionsTable, self.scrollArea_4)
        MainWindow.setTabOrder(self.scrollArea_4, self.answersTable)
        MainWindow.setTabOrder(self.answersTable, self.addNewTopicBox)
        MainWindow.setTabOrder(self.addNewTopicBox, self.addNewTopicButton)
        MainWindow.setTabOrder(self.addNewTopicButton, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.addNewQuestionButton)
        MainWindow.setTabOrder(self.addNewQuestionButton, self.scrollArea_6)
        MainWindow.setTabOrder(self.scrollArea_6, self.lessCheckbox)
        MainWindow.setTabOrder(self.lessCheckbox, self.scrollArea_7)
        MainWindow.setTabOrder(self.scrollArea_7, self.answersListTable)
        MainWindow.setTabOrder(self.answersListTable, self.tabWidget_2)
        MainWindow.setTabOrder(self.tabWidget_2, self.questionsListTable)
        MainWindow.setTabOrder(self.questionsListTable, self.refreshTopicButton)
        MainWindow.setTabOrder(self.refreshTopicButton, self.userEditButton)
        MainWindow.setTabOrder(self.userEditButton, self.examsTypeCombobox)
        MainWindow.setTabOrder(self.examsTypeCombobox, self.startExamButton)
        MainWindow.setTabOrder(self.startExamButton, self.scrollArea)
        MainWindow.setTabOrder(self.scrollArea, self.currentExamTableView)
        MainWindow.setTabOrder(self.currentExamTableView, self.sendExamButton)
        MainWindow.setTabOrder(self.sendExamButton, self.myResultsBarChartButton)
        MainWindow.setTabOrder(self.myResultsBarChartButton, self.showUserResultsBarChartButton)
        MainWindow.setTabOrder(self.showUserResultsBarChartButton, self.resultLessCheckbox)
        MainWindow.setTabOrder(self.resultLessCheckbox, self.resultMoreCheckbox)
        MainWindow.setTabOrder(self.resultMoreCheckbox, self.resultEqualCheckbox)
        MainWindow.setTabOrder(self.resultEqualCheckbox, self.scrollArea_8)
        MainWindow.setTabOrder(self.scrollArea_8, self.usersResultsListTable)
        MainWindow.setTabOrder(self.usersResultsListTable, self.adminButton)
        MainWindow.setTabOrder(self.adminButton, self.filterResultButton)
        MainWindow.setTabOrder(self.filterResultButton, self.examButton)
        MainWindow.setTabOrder(self.examButton, self.profilButton)
        MainWindow.setTabOrder(self.profilButton, self.deleteTopicButton)
        MainWindow.setTabOrder(self.deleteTopicButton, self.editTopicButton)
        MainWindow.setTabOrder(self.editTopicButton, self.deleteQuestionButton)
        MainWindow.setTabOrder(self.deleteQuestionButton, self.editQuestionButton)
        MainWindow.setTabOrder(self.editQuestionButton, self.topicListCombobox)
        MainWindow.setTabOrder(self.topicListCombobox, self.editUserButton)
        MainWindow.setTabOrder(self.editUserButton, self.deleteUserButton)
        MainWindow.setTabOrder(self.deleteUserButton, self.moreChecbox)
        MainWindow.setTabOrder(self.moreChecbox, self.resultsButton)
        MainWindow.setTabOrder(self.resultsButton, self.aboutButton)
        MainWindow.setTabOrder(self.aboutButton, self.logoutButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "pyInstructor - ", None))
        self.adminButton.setText(_translate("MainWindow", "Adminisztráció", None))
        self.profilButton.setText(_translate("MainWindow", "Profil", None))
        self.examButton.setText(_translate("MainWindow", "Vizsgázás", None))
        self.resultsButton.setText(_translate("MainWindow", "Eredmények", None))
        self.aboutButton.setText(_translate("MainWindow", "A programról", None))
        self.logoutButton.setText(_translate("MainWindow", "Kijeletkezés", None))
        self.welcomeLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.currentTimeLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.refreshTopicButton.setText(_translate("MainWindow", "Frissít", None))
        self.addNewQuestionButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Új kérdés és hozzátartozó válaszok hozzáadása.</p></body></html>", None))
        self.addNewQuestionButton.setText(_translate("MainWindow", "Kérdés hozzáadása", None))
        self.editQuestionButton.setToolTip(_translate("MainWindow", "Kérdés és a hozzátartozó válasz(ok) szerkesztése", None))
        self.editQuestionButton.setText(_translate("MainWindow", "Kérdés szerkesztése", None))
        self.deleteQuestionButton.setToolTip(_translate("MainWindow", "Kérdés és a hozzátartozó válasz(ok) törlése", None))
        self.deleteQuestionButton.setText(_translate("MainWindow", "Kérdés törlése", None))
        self.label_22.setText(_translate("MainWindow", "Kérdések:", None))
        item = self.questionsListTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.questionsListTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kérdés szövege", None))
        self.label_23.setText(_translate("MainWindow", "Válaszok:", None))
        item = self.answersListTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.answersListTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Válasz szövege", None))
        item = self.answersListTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "kérdés id", None))
        item = self.answersListTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Helyes-e", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Kérdések és válaszok kezelése", None))
        self.label_36.setText(_translate("MainWindow", "Szűrések:", None))
        self.lessCheckbox.setText(_translate("MainWindow", "<", None))
        self.moreChecbox.setText(_translate("MainWindow", ">", None))
        self.equalCheckbox.setText(_translate("MainWindow", "=", None))
        self.label_28.setText(_translate("MainWindow", "Vezetéknév:", None))
        self.emailFilterBox.setPlaceholderText(_translate("MainWindow", "email@cim.hu", None))
        self.ageFilterBox.setPlaceholderText(_translate("MainWindow", "1970-03-15", None))
        self.filterUsersButton.setText(_translate("MainWindow", "Szűrés", None))
        self.lastNameFilterBox.setPlaceholderText(_translate("MainWindow", "Nagy", None))
        self.label_35.setText(_translate("MainWindow", "Regisztrálás dátuma:", None))
        self.addressFilterBox.setPlaceholderText(_translate("MainWindow", "Fő út 9.", None))
        self.label_32.setText(_translate("MainWindow", "Cím:", None))
        self.cityFilterBox.setPlaceholderText(_translate("MainWindow", "Budapest", None))
        self.label_33.setText(_translate("MainWindow", "Város:", None))
        self.label_30.setText(_translate("MainWindow", "Születetési idő:", None))
        self.label_34.setText(_translate("MainWindow", "Telefonszám:", None))
        self.label_31.setText(_translate("MainWindow", "Email:", None))
        self.phoneFilterBox.setPlaceholderText(_translate("MainWindow", "+301234567", None))
        self.label_29.setText(_translate("MainWindow", "Keresztnév:", None))
        self.firstNameFilterBox.setPlaceholderText(_translate("MainWindow", "Elek", None))
        self.registeredFilterBox.setPlaceholderText(_translate("MainWindow", "2010-01-14", None))
        self.editUserButton.setText(_translate("MainWindow", "Felhasználó szerkesztése", None))
        self.deleteUserButton.setText(_translate("MainWindow", "Felhasználó törlése", None))
        item = self.usersListTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.usersListTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Név", None))
        item = self.usersListTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email", None))
        item = self.usersListTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Regisztrált", None))
        item = self.usersListTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Város", None))
        item = self.usersListTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Cím", None))
        item = self.usersListTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Telefonszám", None))
        item = self.usersListTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Születési idő", None))
        item = self.usersListTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Jogosultság", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Felhasználók kezelése", None))
        item = self.answersTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.answersTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Válasz szövege", None))
        item = self.answersTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Kérédés id", None))
        item = self.answersTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Helyes válasz-e", None))
        self.label_21.setText(_translate("MainWindow", "Új témakör hozzáadása:", None))
        self.addNewTopicButton.setText(_translate("MainWindow", "Hozzáad", None))
        item = self.topicsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.topicsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Témakör neve", None))
        self.label_12.setText(_translate("MainWindow", "Kérdéshez tartozó válaszok:", None))
        item = self.questionsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.questionsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kérdés szövege", None))
        self.label_10.setText(_translate("MainWindow", "Témához tartozó kérdések:", None))
        self.label_11.setText(_translate("MainWindow", "Témakörök listája:", None))
        self.deleteTopicButton.setText(_translate("MainWindow", "Téma törlése", None))
        self.editTopicButton.setText(_translate("MainWindow", "Téma szerkesztése", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Témakörök kezelése", None))
        self.label_14.setText(_translate("MainWindow", "(Kötelező mező)", None))
        self.label_20.setText(_translate("MainWindow", "Telefonszám:", None))
        self.label_18.setText(_translate("MainWindow", "(Kötelező mező)", None))
        self.label_17.setText(_translate("MainWindow", "(Kötelező mező)", None))
        self.label_16.setText(_translate("MainWindow", "(Kötelező mező)", None))
        self.label_6.setText(_translate("MainWindow", "Vezetéknév:", None))
        self.label_13.setText(_translate("MainWindow", "Város:", None))
        self.label_5.setText(_translate("MainWindow", "Keresztnév:", None))
        self.label_9.setText(_translate("MainWindow", "Jelszó újra:", None))
        self.label_8.setText(_translate("MainWindow", "Jelszó:", None))
        self.label_19.setText(_translate("MainWindow", "Cím:", None))
        self.label_15.setText(_translate("MainWindow", "(Kötelező mező)", None))
        self.label_7.setText(_translate("MainWindow", "Email:", None))
        self.label_38.setText(_translate("MainWindow", "Születési idő:", None))
        self.userEditButton.setText(_translate("MainWindow", "Módosít", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Alap adatok", None))
        self.label_2.setText(_translate("MainWindow", "Válassz témakört:", None))
        self.maxPointLabelText.setText(_translate("MainWindow", "Elérhető maximális pontszám:", None))
        self.label_3.setText(_translate("MainWindow", "Hátralévő idő:", None))
        self.startExamButton.setText(_translate("MainWindow", "Vizsga indítása", None))
        self.yourResultLabelText.setText(_translate("MainWindow", "Pontszámod:", None))
        self.sendExamButton.setText(_translate("MainWindow", "Elküld", None))
        self.myResultsBarChartButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Saját pontjaim mutatása témakörönként oszlopdiagrammal</p></body></html>", None))
        self.myResultsBarChartButton.setText(_translate("MainWindow", "Saját pontjaim", None))
        self.showUserResultsBarChartButton.setToolTip(_translate("MainWindow", "Kiválasztott felhasználó eredményeinek mutatása oszlopdiagrammal", None))
        self.showUserResultsBarChartButton.setText(_translate("MainWindow", "Felhasználó pontjai", None))
        self.label_37.setText(_translate("MainWindow", "Szűrések:", None))
        self.resultLessCheckbox.setText(_translate("MainWindow", "<", None))
        self.resultMoreCheckbox.setText(_translate("MainWindow", ">", None))
        self.resultEqualCheckbox.setText(_translate("MainWindow", "=", None))
        self.label_25.setText(_translate("MainWindow", "Vizsga dátuma:", None))
        self.label_27.setText(_translate("MainWindow", "Témakör:", None))
        self.label_26.setText(_translate("MainWindow", "Pontszám:", None))
        self.topicsFilterBox.setPlaceholderText(_translate("MainWindow", "python", None))
        self.filterResultButton.setText(_translate("MainWindow", "Szűrés", None))
        self.scoreFilterBox.setPlaceholderText(_translate("MainWindow", "16", None))
        self.topicsDateFilterBox.setPlaceholderText(_translate("MainWindow", "2014-08-30", None))
        self.label_39.setText(_translate("MainWindow", "Email:", None))
        self.resultPageEmailFilterBox.setPlaceholderText(_translate("MainWindow", "emailcim@gmail.com", None))
        self.label_4.setText(_translate("MainWindow", "Keresztnév", None))
        self.label.setText(_translate("MainWindow", "Vezetéknév:", None))
        self.resultPageFirstNameFilterBox.setPlaceholderText(_translate("MainWindow", "János", None))
        self.resultPageLastNameFilterBox.setPlaceholderText(_translate("MainWindow", "Kovács", None))
        item = self.usersResultsListTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.usersResultsListTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Név", None))
        item = self.usersResultsListTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email", None))
        item = self.usersResultsListTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Témakör", None))
        item = self.usersResultsListTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Pontszám", None))
        item = self.usersResultsListTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Vizsga dátuma", None))

import dashboardResource_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

