# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editUserView.ui'
#
# Created: Tue Nov 11 22:45:47 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(318, 393)
        MainWindow.setFixedSize(318, 393) # méretezés letiltása
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cityEditBox = QtGui.QLineEdit(self.centralwidget)
        self.cityEditBox.setObjectName(_fromUtf8("cityEditBox"))
        self.gridLayout.addWidget(self.cityEditBox, 6, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 12, 0, 1, 1)
        self.privilidgeEditComboBox = QtGui.QComboBox(self.centralwidget)
        self.privilidgeEditComboBox.setObjectName(_fromUtf8("privilidgeEditComboBox"))
        self.gridLayout.addWidget(self.privilidgeEditComboBox, 14, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 9, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 11, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 1, 0, 1, 1)
        self.lastNameEditBox = QtGui.QLineEdit(self.centralwidget)
        self.lastNameEditBox.setObjectName(_fromUtf8("lastNameEditBox"))
        self.gridLayout.addWidget(self.lastNameEditBox, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 10, 0, 1, 1)
        self.firstNameEditBox = QtGui.QLineEdit(self.centralwidget)
        self.firstNameEditBox.setObjectName(_fromUtf8("firstNameEditBox"))
        self.gridLayout.addWidget(self.firstNameEditBox, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 14, 0, 1, 1)
        self.addressEditBox = QtGui.QLineEdit(self.centralwidget)
        self.addressEditBox.setObjectName(_fromUtf8("addressEditBox"))
        self.gridLayout.addWidget(self.addressEditBox, 8, 1, 1, 1)
        self.birthDayEditBox = QtGui.QLineEdit(self.centralwidget)
        self.birthDayEditBox.setObjectName(_fromUtf8("birthDayEditBox"))
        self.gridLayout.addWidget(self.birthDayEditBox, 12, 1, 1, 1)
        self.phoneEditBox = QtGui.QLineEdit(self.centralwidget)
        self.phoneEditBox.setObjectName(_fromUtf8("phoneEditBox"))
        self.gridLayout.addWidget(self.phoneEditBox, 10, 1, 1, 1)
        self.emailEditBox = QtGui.QLineEdit(self.centralwidget)
        self.emailEditBox.setObjectName(_fromUtf8("emailEditBox"))
        self.gridLayout.addWidget(self.emailEditBox, 4, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 13, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.editUserButton = QtGui.QPushButton(self.centralwidget)
        self.editUserButton.setObjectName(_fromUtf8("editUserButton"))
        self.horizontalLayout.addWidget(self.editUserButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lastNameEditBox, self.firstNameEditBox)
        MainWindow.setTabOrder(self.firstNameEditBox, self.emailEditBox)
        MainWindow.setTabOrder(self.emailEditBox, self.cityEditBox)
        MainWindow.setTabOrder(self.cityEditBox, self.addressEditBox)
        MainWindow.setTabOrder(self.addressEditBox, self.phoneEditBox)
        MainWindow.setTabOrder(self.phoneEditBox, self.birthDayEditBox)
        MainWindow.setTabOrder(self.birthDayEditBox, self.privilidgeEditComboBox)
        MainWindow.setTabOrder(self.privilidgeEditComboBox, self.editUserButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Felhasználó szerkesztése", None))
        self.label_6.setText(_translate("MainWindow", "Születési idő:", None))
        self.label_2.setText(_translate("MainWindow", "Keresztnév:", None))
        self.label.setText(_translate("MainWindow", "Vezetéknév:", None))
        self.label_4.setText(_translate("MainWindow", "Város:", None))
        self.label_3.setText(_translate("MainWindow", "Email:", None))
        self.label_7.setText(_translate("MainWindow", "Telefonszám:", None))
        self.label_5.setText(_translate("MainWindow", "Cím:", None))
        self.label_8.setText(_translate("MainWindow", "Jogosultság:", None))
        self.editUserButton.setText(_translate("MainWindow", "Szerkeszt", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

